# Generated by Django 6.0.5 on 2026-05-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MacBookSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('MacBook Air', 'MacBook Air'), ('MacBook Pro', 'MacBook Pro')], max_length=20, verbose_name='Лінійка')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('chip', models.CharField(max_length=50, verbose_name='Чіп')),
                ('cpu_cores', models.PositiveSmallIntegerField(verbose_name='CPU ядра')),
                ('gpu_cores', models.PositiveSmallIntegerField(verbose_name='GPU ядра')),
                ('ram', models.CharField(choices=[('8GB', '8 GB'), ('16GB', '16 GB'), ('24GB', '24 GB'), ('32GB', '32 GB'), ('48GB', '48 GB'), ('64GB', '64 GB'), ('128GB', '128 GB')], max_length=10, verbose_name='RAM')),
                ('storage', models.CharField(choices=[('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB')], max_length=10, verbose_name='Накопичувач')),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Діагональ (дюйм)')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип дисплею')),
                ('battery_hours', models.PositiveSmallIntegerField(verbose_name='Батарея (год)')),
                ('has_touch_id', models.BooleanField(default=True, verbose_name='Touch ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macbook_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація MacBook',
            },
        ),
        migrations.CreateModel(
            name='IPhoneSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('storage', models.CharField(choices=[('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB')], max_length=10, verbose_name='Накопичувач')),
                ('chip', models.CharField(max_length=50, verbose_name='Чіп')),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Діагональ екрана (дюйм)')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип дисплею')),
                ('ram', models.CharField(choices=[('8GB', '8 GB'), ('16GB', '16 GB'), ('24GB', '24 GB'), ('32GB', '32 GB'), ('48GB', '48 GB'), ('64GB', '64 GB'), ('128GB', '128 GB')], max_length=10, verbose_name='RAM')),
                ('main_camera', models.CharField(max_length=100, verbose_name='Основна камера')),
                ('front_camera', models.CharField(max_length=100, verbose_name='Фронтальна камера')),
                ('battery_mah', models.PositiveIntegerField(verbose_name='Батарея (мАг)')),
                ('has_5g', models.BooleanField(default=True, verbose_name='5G')),
                ('has_esim', models.BooleanField(default=True, verbose_name='eSIM')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iphone_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація iPhone',
            },
        ),
        migrations.CreateModel(
            name='IPadSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('iPad', 'iPad'), ('iPad mini', 'iPad mini'), ('iPad Air', 'iPad Air'), ('iPad Pro', 'iPad Pro')], max_length=20, verbose_name='Лінійка')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('storage', models.CharField(choices=[('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB')], max_length=10, verbose_name='Накопичувач')),
                ('chip', models.CharField(max_length=50, verbose_name='Чіп')),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Діагональ (дюйм)')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип дисплею')),
                ('ram', models.CharField(choices=[('8GB', '8 GB'), ('16GB', '16 GB'), ('24GB', '24 GB'), ('32GB', '32 GB'), ('48GB', '48 GB'), ('64GB', '64 GB'), ('128GB', '128 GB')], max_length=10, verbose_name='RAM')),
                ('has_cellular', models.BooleanField(default=False, verbose_name='Cellular')),
                ('has_pencil', models.BooleanField(default=True, verbose_name='Підтримка Apple Pencil')),
                ('pencil_gen', models.CharField(blank=True, max_length=50, verbose_name='Покоління Pencil')),
                ('battery_hours', models.PositiveSmallIntegerField(verbose_name='Батарея (год)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipad_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація iPad',
            },
        ),
        migrations.CreateModel(
            name='IMacSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('chip', models.CharField(max_length=50, verbose_name='Чіп')),
                ('cpu_cores', models.PositiveSmallIntegerField(verbose_name='CPU ядра')),
                ('gpu_cores', models.PositiveSmallIntegerField(verbose_name='GPU ядра')),
                ('ram', models.CharField(choices=[('8GB', '8 GB'), ('16GB', '16 GB'), ('24GB', '24 GB'), ('32GB', '32 GB'), ('48GB', '48 GB'), ('64GB', '64 GB'), ('128GB', '128 GB')], max_length=10, verbose_name='RAM')),
                ('storage', models.CharField(choices=[('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB')], max_length=10, verbose_name='Накопичувач')),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Діагональ (дюйм)')),
                ('resolution', models.CharField(max_length=50, verbose_name='Роздільна здатність')),
                ('camera_mp', models.PositiveSmallIntegerField(verbose_name='Камера (Мп)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imac_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація iMac',
            },
        ),
        migrations.CreateModel(
            name='AppleWatchSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('Series', 'Apple Watch Series'), ('SE', 'Apple Watch SE'), ('Ultra', 'Apple Watch Ultra')], max_length=20, verbose_name='Лінійка')),
                ('generation', models.CharField(max_length=50, verbose_name='Покоління')),
                ('color', models.CharField(max_length=100, verbose_name='Колір корпусу')),
                ('band_color', models.CharField(max_length=100, verbose_name='Колір ремінця')),
                ('band_material', models.CharField(max_length=100, verbose_name='Матеріал ремінця')),
                ('case_size_mm', models.PositiveSmallIntegerField(verbose_name='Розмір корпусу (мм)')),
                ('case_material', models.CharField(choices=[('Aluminum', 'Алюміній'), ('Steel', 'Нержавіюча сталь'), ('Titanium', 'Титан')], max_length=20, verbose_name='Матеріал корпусу')),
                ('has_cellular', models.BooleanField(default=False, verbose_name='Cellular')),
                ('chip', models.CharField(max_length=50, verbose_name='Чіп')),
                ('battery_hours', models.PositiveSmallIntegerField(verbose_name='Батарея (год)')),
                ('water_resist', models.CharField(max_length=50, verbose_name='Захист від води')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація Apple Watch',
            },
        ),
        migrations.CreateModel(
            name='AppleMouseSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('connection', models.CharField(choices=[('Wireless', 'Бездротова (Bluetooth)'), ('USB-C', 'USB-C')], max_length=20, verbose_name='Підключення')),
                ('has_multi_touch', models.BooleanField(default=True, verbose_name='Multi-Touch поверхня')),
                ('battery_months', models.PositiveSmallIntegerField(verbose_name='Батарея (міс)')),
                ('charge_port', models.CharField(max_length=20, verbose_name="Роз'єм зарядки")),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація мишки Apple',
            },
        ),
        migrations.CreateModel(
            name='AppleKeyboardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('layout', models.CharField(choices=[('UA', 'Українська'), ('EN', 'Англійська'), ('RU', 'Російська')], max_length=5, verbose_name='Розкладка')),
                ('connection', models.CharField(choices=[('Wireless', 'Бездротова (Bluetooth)'), ('USB-C', 'USB-C')], max_length=20, verbose_name='Підключення')),
                ('has_touch_id', models.BooleanField(default=False, verbose_name='Touch ID')),
                ('has_numpad', models.BooleanField(default=False, verbose_name='Цифровий блок')),
                ('battery_months', models.PositiveSmallIntegerField(verbose_name='Батарея (міс)')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація клавіатури Apple',
            },
        ),
        migrations.CreateModel(
            name='AirPodsSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('AirPods', 'AirPods'), ('AirPods Pro', 'AirPods Pro'), ('AirPods Max', 'AirPods Max')], max_length=20, verbose_name='Лінійка')),
                ('generation', models.CharField(max_length=50, verbose_name='Покоління')),
                ('color', models.CharField(max_length=100, verbose_name='Колір')),
                ('has_anc', models.BooleanField(default=False, verbose_name='Активне шумоподавлення (ANC)')),
                ('has_transparency', models.BooleanField(default=False, verbose_name='Режим прозорості')),
                ('chip', models.CharField(max_length=50, verbose_name='Чіп')),
                ('battery_earbuds', models.PositiveSmallIntegerField(verbose_name='Батарея навушників (год)')),
                ('battery_case', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Батарея кейсу (год)')),
                ('case_connector', models.CharField(choices=[('Lightning', 'Lightning'), ('USB-C', 'USB-C'), ('MagSafe', 'MagSafe')], max_length=20, verbose_name="Роз'єм кейсу")),
                ('is_wireless_charge', models.BooleanField(default=True, verbose_name='Бездротова зарядка')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='airpods_spec', to='store.product')),
            ],
            options={
                'verbose_name': 'Специфікація AirPods',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'ordering': ['order'],
            },
        ),
    ]
