# Generated by Django 6.0.5 on 2026-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iphone', 'iPhone'), ('ipad', 'iPad'), ('macbook', 'MacBook'), ('imac', 'iMac'), ('watch', 'Apple Watch'), ('airpods', 'AirPods'), ('keyboard', 'Клавіатура'), ('mouse', 'Мишка')], max_length=20, verbose_name='Категорія'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
