# Generated by Django 6.0.5 on 2026-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productvariant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='new_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Новинка до'),
        ),
    ]
