# Generated by Django 6.0.5 on 2026-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productvariant_is_new_productvariant_new_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Ціна'),
        ),
    ]
