@baseUrl = http://127.0.0.1:8000/api/v1
@rootUrl = http://127.0.0.1:8000
@contentType = application/json

# API DOCS

### Swagger UI
GET {{rootUrl}}/api/docs/

### OpenAPI schema
GET {{rootUrl}}/api/schema/


# PRODUCTS

### List products
GET {{baseUrl}}/products/

### Product detail by slug
GET {{baseUrl}}/products/iphone-17-pro/

### Filter by category
GET {{baseUrl}}/products/?category=iphone

### Search by product text and variant attributes
GET {{baseUrl}}/products/?search=iPhone

### Filter by variant fields
GET {{baseUrl}}/products/?color=Silver&storage=256GB&min_price=40000&max_price=70000&in_stock=true

### Filter by dynamic attributes
GET {{baseUrl}}/products/?attr_chip=A19%20Pro

### Sort by lowest variant price
GET {{baseUrl}}/products/?ordering=price

### Sort by newest products
GET {{baseUrl}}/products/?ordering=-created_at
