@baseUrl = http://127.0.0.1:8000/api/v1
@contentType = application/json

# PRODUCTS

### List products
GET {{baseUrl}}/products/

### Product detail by slug
GET {{baseUrl}}/products/iphone-17-pro/

### Filter by category
GET {{baseUrl}}/products/?category=iphone

### Search by product text and variant attributes
GET {{baseUrl}}/products/?search=iPhone

### Filter by variant fields
GET {{baseUrl}}/products/?color=Silver&storage=256GB&min_price=40000&max_price=70000&in_stock=true

### Filter by dynamic attributes
GET {{baseUrl}}/products/?attr_chip=A19%20Pro

### Sort by lowest variant price
GET {{baseUrl}}/products/?ordering=price

### Sort by newest products
GET {{baseUrl}}/products/?ordering=-created_at


# CREATE PRODUCT WITH VARIANTS AND ATTRIBUTES

### Create iPhone product
POST {{baseUrl}}/products/
Content-Type: {{contentType}}

{
  "category": "iphone",
  "name": "iPhone 17 Pro",
  "description": "iPhone 17 Pro with configurable colors and storage.",
  "is_active": true,
  "variants": [
    {
      "color": "Silver",
      "storage": "256GB",
      "price": "54999.00",
      "old_price": null,
      "stock": 5,
      "attributes": [
        {
          "name": "display_size",
          "value": "6.3"
        },
        {
          "name": "chip",
          "value": "A19 Pro"
        },
        {
          "name": "ram",
          "value": "8GB"
        },
        {
          "name": "sim",
          "value": "eSIM"
        }
      ]
    },
    {
      "color": "Silver",
      "storage": "512GB",
      "price": "64999.00",
      "old_price": null,
      "stock": 3,
      "attributes": [
        {
          "name": "display_size",
          "value": "6.3"
        },
        {
          "name": "chip",
          "value": "A19 Pro"
        },
        {
          "name": "ram",
          "value": "8GB"
        },
        {
          "name": "sim",
          "value": "eSIM"
        }
      ]
    }
  ]
}


###

# UPDATE / DELETE

### Update base product fields
PATCH {{baseUrl}}/products/iphone-17-pro/
Content-Type: {{contentType}}

{
  "description": "Updated product description."
}

### Hide product from public API
PATCH {{baseUrl}}/products/iphone-17-pro/
Content-Type: {{contentType}}

{
  "is_active": false
}

### Delete product
DELETE {{baseUrl}}/products/iphone-17-pro/
